name: Compilar e implementar la aplicación de .NET Core en la aplicación web bdd-workshop-hector-betancourt

on:
  push:
    branches:
    - master

env:
  AZURE_WEBAPP_NAME: bdd-workshop-hector-betancourt
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: bdd.workshop.calculator.web

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [development, staging, production]  # Define tus entornos aquí
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.WORKING_DIRECTORY }}/published"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: "${{ env.WORKING_DIRECTORY }}/published"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        environment: [development, staging, production]  # Define tus entornos aquí
    steps:
    - name: Descargar el artefacto del trabajo de compilación
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: "${{ env.WORKING_DIRECTORY }}/published"
    - name: Implementar en Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: "${{ env.AZURE_WEBAPP_NAME }}-${{ matrix.environment }}"
        publish-profile: ${{ secrets["bdd_workshop_hector_betancourt_BC8B"] }}
        package: "${{ env.WORKING_DIRECTORY }}/published"
