name: Build-Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: '88.0.4324.96'
    - run: |
        export DISPLAY=:99
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release
      
    - name: Publish with dotnet
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to myasp.net
      uses: myaspnet/run-actions@v1
      with:
        publish-profile: ${{ secrets.MYASPNET_PUBLISH_PROFILE }}
