- name: Setup .NET 8.0
  uses: actions/setup-dotnet@v3
      with:
        # Semantic version range syntax or exact version of a dotnet version
        dotnet-version: '8.0'
        cache: true
      steps:
        - uses: actions/checkout@v4
        - name: Setup dotnet
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '6.0.x'
        - name: Install dependencies
          run: dotnet restore
