name: Test bdd-workshop-hector-betancourt

on:
  push:
    branches:
      - tests
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release
        
      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test
